version: "3"

# TODO: add db
services:
  nginx:
    image: farqlia/nginx:v1
    ports:
      # maps {HOST_PORT}:{CONTAINER_PORT}
      - "81:81"
    depends_on:
      - daphne
    networks:
      - front
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - back
  daphne:
    image: farqlia/daphne:v2
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HOST=${HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    ports:
      - "9542:9542"
    depends_on:
      - redis
    networks:
      - front
      - back
networks:
  front:
  back:
