version: "3"

# TODO: add db
services:
  nginx:
    image: farqlia/nginx
    ports:
      # maps {HOST_PORT}:{CONTAINER_PORT}
      - "81:81"
    depends_on:
      - daphne
    networks:
      - front
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - back
  daphne:
    image: "637423251640.dkr.ecr.us-east-1.amazonaws.com/myfront:v4"
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
    ports:
      - "9542:9542"
    depends_on:
      - redis
    networks:
      - front
      - back
networks:
  front:
  back:
